"""Initial migration

Revision ID: 643390290104
Revises: 
Create Date: 2024-02-21 15:03:22.405956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643390290104'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
